version: '3.8'

services:
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    ports:
      - "8081:8080"
    volumes:
      - ./data:/label-studio/data
    restart: unless-stopped
    user: "1001:1001"
